testing cancel job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,37 +1,53 @@
-version: 2.1
-
-executors:
-  linux:
-    docker:
-      - image: cimg/base:2020.01
-  macos:
-    macos:
-      xcode: 11.4
-
-orbs:
-  node: circleci/node@2.0.0
-
+version: 2
 jobs:
-  test:
-    parameters:
-      os:
-        type: executor
-      node-version:
-        type: string
-    executor: << parameters.os >>
+  failed-job:
+    docker:
+      - image: circleci/golang:1.11.0
     steps:
       - checkout
-      - node/install:
-          node-version: << parameters.node-version >>
-          install-yarn: true
+      - run: sleep 30
+      - run: exit 1
+  job-1:
+    docker:
+      - image: circleci/golang:1.11.0
+    steps:
+      - checkout
+      - run: sleep 60
+  job-2:
+    docker:
+      - image: circleci/golang:1.11.0
+    steps:
+      - checkout
+      - run: sleep 60
+  auto-cancel:
+    docker:
+      - image: circleci/golang:1.11.0
+    steps:
+      - checkout
       - run:
-          command: echo "running matrix job for ${<< parameters.os >>} ${<< parameters.node-version >>}"
-
+          name: auto-cancel
+          command: |
+            while true; do
+              json=$(curl -s -H 'Accept: application/json' -X GET https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/job?circle-token=${CIRCLECI_TOKEN})
+              is_failed=$(echo $json | jq '.items | any(.status == "failed")')
+              is_pending=$(echo $json | jq '.items | any(.status == "running")')
+              if [ "$is_failed" == "true" ]; then
+                echo "Cancel workflow"
+                curl -s -H 'Accept: application/json' -X POST https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel?circle-token=${CIRCLECI_TOKEN}
+                exit 0
+              elif [ "$is_pending" == "false" ]; then
+                echo "other jobs finished"
+                exit 0
+              else
+                echo "waiting other jobs"
+              fi
+              sleep 10
+            done
 workflows:
-  all-tests:
+  version: 2
+  auto-cancel-example:
     jobs:
-      - test:
-          matrix:
-            parameters:
-              os: [linux, macos]
-              node-version: ["10.9.0", "11.9.0", "12.9.1", "13.9.0"]
+      - failed-job
+      - job-1
+      - job-2
+      - auto-cancel
